const products = [
  {
    _id: "1",
    name: "נר שעווה 1",
    image: "/images/(1).jpg",
    description: "נר שעווה 1",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "נר שעווה 2",
    image: "/images/(2).jpg",
    description: "נר שעווה 2",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "נר שווה 3",
    image: "/images/(7).jpg",
    description: "נר שווה 3",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "נר שווה 4",
    image: "/images/(4).jpg",
    description: "נר שווה 4",
    brand: "Sony",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "נר שווה 5",
    image: "/images/(5).jpg",
    description: "נר שווה 5",
    brand: "Logitech",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "נר שווה 6",
    image: "/images/(6).jpg",
    description: "נר שווה 6",
    brand: "Amazon",
    category: "Electronics",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
